name: Publish to website branch
on:
  workflow_dispatch:
  push:
    branches:
      - main
      
jobs:
  publish:
    name: publish to website branch

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: retypeapp/action-build@latest

      - uses: retypeapp/action-github-pages@latest
        with:
          branch: website
          update-branch: true
