name: Publish to website branch
on:
  workflow_dispatch:
  push:
    branches:
      - main
      
jobs:
  publish:
    name: publish to website branch

    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - uses: retypeapp/action-build@multi

      - uses: retypeapp/action-github-pages@latest
        with:
          update-branch: true
